version: "3.7"

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mymongodbdev
      - MONGO_INITDB_ROOT_PASSWORD=mymongodbdev
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
