### User register
POST http://localhost:8000/api/v1/register
content-type: application/json

{
  "name": "Dito",
  "email": "dito@me.com",
  "password": "dito123dito"
}

### User Login
POST http://localhost:8000/api/v1/login
content-type: application/json

{
  "email": "dito@me.com",
  "password": "dito123dito"
}
