### User register
POST http://103.82.92.144:8000/api/v1/user
content-type: application/json

{
  "name": "Dito",
  "email": "dito@me.com",
  "password": "dito123dito"
}

### User Login
POST http://103.82.92.144:8000/api/v1/user/login
content-type: application/json

{
  "email": "dito@me.com",
  "password": "dito123dito"
}

### User Logout
POST http://103.82.92.144:8000/api/v1/user/logout
